### ISSUE TITLE
Plugin cause TypeError when generating

### ISSUE THREAD

**Issue by tilmans** [hcoona/hexo-renderer-asciidoc#3]
After adding the plugin to my hexo project I get the following error when running `hexo generate`:

```
/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/index.js:91
      this.stack[k].value = null
                          ^

TypeError: Cannot assign to read only property 'value' of true
    at Parser.parser.onValue (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/index.js:91:27)
    at Parser.proto.emit (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:265:8)
    at Parser.proto.onToken (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:276:12)
    at Parser.parser.onToken (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/index.js:96:12)
    at Parser.proto.write (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:202:20)
    at Stream.<anonymous> (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/warehouse/node_modules/JSONStream/node_modules/through/index.js:26:11)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1748:12)
    at callback (/Users/tschlenk/Code/doc/platform/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:207:17)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
```

Here's the list of all installed modules, Node.js is v4.2.1:

```
hexo-site@0.0.0 /...
├─┬ hexo@3.1.1
│ ├── abbrev@1.0.7
│ ├── archy@1.0.0
│ ├── bluebird@2.10.2
│ ├─┬ bunyan@1.5.1
│ │ ├─┬ dtrace-provider@0.6.0
│ │ │ └── nan@2.1.0
│ │ ├─┬ mv@2.1.1
│ │ │ ├─┬ mkdirp@0.5.1
│ │ │ │ └── minimist@0.0.8
│ │ │ ├── ncp@2.0.0
│ │ │ └─┬ rimraf@2.4.5
│ │ │   └─┬ glob@6.0.3
│ │ │     ├─┬ inflight@1.0.4
│ │ │     │ └── wrappy@1.0.1
│ │ │     ├── inherits@2.0.1
│ │ │     ├─┬ once@1.3.3
│ │ │     │ └── wrappy@1.0.1
│ │ │     └── path-is-absolute@1.0.0
│ │ └── safe-json-stringify@1.0.3
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── escape-string-regexp@1.0.4
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├─┬ strip-ansi@3.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ cheerio@0.19.0
│ │ ├─┬ css-select@1.0.0
│ │ │ ├── boolbase@1.0.0
│ │ │ ├── css-what@1.0.0
│ │ │ ├─┬ domutils@1.4.3
│ │ │ │ └── domelementtype@1.3.0
│ │ │ └── nth-check@1.0.1
│ │ ├─┬ dom-serializer@0.1.0
│ │ │ └── domelementtype@1.1.3
│ │ ├── entities@1.1.1
│ │ └─┬ htmlparser2@3.8.3
│ │   ├── domelementtype@1.3.0
│ │   ├── domhandler@2.3.0
│ │   ├── domutils@1.5.1
│ │   ├── entities@1.0.0
│ │   └─┬ readable-stream@1.1.13
│ │     ├── core-util-is@1.0.2
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├─┬ hexo-cli@0.1.9
│ │ ├── bluebird@3.1.1
│ │ └── minimist@1.2.0
│ ├── hexo-front-matter@0.2.2
│ ├─┬ hexo-fs@0.1.5
│ │ ├── bluebird@3.1.1
│ │ ├─┬ chokidar@1.4.2
│ │ │ ├─┬ anymatch@1.3.0
│ │ │ │ ├── arrify@1.0.1
│ │ │ │ └─┬ micromatch@2.3.7
│ │ │ │   ├─┬ arr-diff@2.0.0
│ │ │ │   │ └── arr-flatten@1.0.1
│ │ │ │   ├── array-unique@0.2.1
│ │ │ │   ├─┬ braces@1.8.3
│ │ │ │   │ ├─┬ expand-range@1.8.1
│ │ │ │   │ │ └─┬ fill-range@2.2.3
│ │ │ │   │ │   ├── is-number@2.1.0
│ │ │ │   │ │   ├─┬ isobject@2.0.0
│ │ │ │   │ │   │ └── isarray@0.0.1
│ │ │ │   │ │   ├── randomatic@1.1.5
│ │ │ │   │ │   └── repeat-string@1.5.2
│ │ │ │   │ ├── preserve@0.2.0
│ │ │ │   │ └── repeat-element@1.1.2
│ │ │ │   ├── expand-brackets@0.1.4
│ │ │ │   ├─┬ extglob@0.3.1
│ │ │ │   │ ├─┬ ansi-green@0.1.1
│ │ │ │   │ │ └── ansi-wrap@0.1.0
│ │ │ │   │ └── success-symbol@0.1.0
│ │ │ │   ├── filename-regex@2.0.0
│ │ │ │   ├── is-extglob@1.0.0
│ │ │ │   ├─┬ kind-of@3.0.2
│ │ │ │   │ └── is-buffer@1.1.1
│ │ │ │   ├── normalize-path@2.0.1
│ │ │ │   ├─┬ object.omit@2.0.0
│ │ │ │   │ ├─┬ for-own@0.1.3
│ │ │ │   │ │ └── for-in@0.1.4
│ │ │ │   │ └── is-extendable@0.1.1
│ │ │ │   ├─┬ parse-glob@3.0.4
│ │ │ │   │ ├── glob-base@0.3.0
│ │ │ │   │ └── is-dotfile@1.0.2
│ │ │ │   └─┬ regex-cache@0.4.2
│ │ │ │     ├── is-equal-shallow@0.1.3
│ │ │ │     └── is-primitive@2.0.0
│ │ │ ├── async-each@0.1.6
│ │ │ ├─┬ fsevents@1.0.6
│ │ │ │ ├── ansi@0.3.0
│ │ │ │ ├── ansi-regex@2.0.0
│ │ │ │ ├── ansi-styles@2.1.0
│ │ │ │ ├── are-we-there-yet@1.0.4
│ │ │ │ ├── asn1@0.2.3
│ │ │ │ ├── assert-plus@0.1.5
│ │ │ │ ├── async@1.5.0
│ │ │ │ ├── aws-sign2@0.6.0
│ │ │ │ ├─┬ bl@1.0.0
│ │ │ │ │ └─┬ readable-stream@2.0.4
│ │ │ │ │   ├── core-util-is@1.0.2
│ │ │ │ │   ├── inherits@2.0.1
│ │ │ │ │   ├── isarray@0.0.1
│ │ │ │ │   ├── process-nextick-args@1.0.3
│ │ │ │ │   ├── string_decoder@0.10.31
│ │ │ │ │   └── util-deprecate@1.0.2
│ │ │ │ ├── block-stream@0.0.8
│ │ │ │ ├── boom@2.10.1
│ │ │ │ ├── caseless@0.11.0
│ │ │ │ ├── chalk@1.1.1
│ │ │ │ ├── combined-stream@1.0.5
│ │ │ │ ├── commander@2.9.0
│ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ ├── dashdash@1.10.1
│ │ │ │ ├── debug@0.7.4
│ │ │ │ ├── deep-extend@0.4.0
│ │ │ │ ├── delayed-stream@1.0.0
│ │ │ │ ├── delegates@0.1.0
│ │ │ │ ├── ecc-jsbn@0.1.1
│ │ │ │ ├── escape-string-regexp@1.0.3
│ │ │ │ ├── extend@3.0.0
│ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ ├── forever-agent@0.6.1
│ │ │ │ ├── form-data@1.0.0-rc3
│ │ │ │ ├── fstream@1.0.8
│ │ │ │ ├─┬ fstream-ignore@1.0.3
│ │ │ │ │ └─┬ minimatch@3.0.0
│ │ │ │ │   └─┬ brace-expansion@1.1.1
│ │ │ │ │     ├── balanced-match@0.2.1
│ │ │ │ │     └── concat-map@0.0.1
│ │ │ │ ├── gauge@1.2.2
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├── generate-object-property@1.2.0
│ │ │ │ ├── graceful-fs@4.1.2
│ │ │ │ ├── graceful-readlink@1.0.1
│ │ │ │ ├── har-validator@2.0.3
│ │ │ │ ├── has-ansi@2.0.0
│ │ │ │ ├── has-unicode@1.0.1
│ │ │ │ ├── hawk@3.1.2
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ ├── http-signature@1.1.0
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ ├── ini@1.3.4
│ │ │ │ ├── is-my-json-valid@2.12.3
│ │ │ │ ├── is-property@1.0.2
│ │ │ │ ├── is-typedarray@1.0.0
│ │ │ │ ├── isarray@0.0.1
│ │ │ │ ├── isstream@0.1.2
│ │ │ │ ├── jodid25519@1.0.2
│ │ │ │ ├── jsbn@0.1.0
│ │ │ │ ├── json-schema@0.2.2
│ │ │ │ ├── json-stringify-safe@5.0.1
│ │ │ │ ├── jsonpointer@2.0.0
│ │ │ │ ├── jsprim@1.2.2
│ │ │ │ ├── lodash._basetostring@3.0.1
│ │ │ │ ├── lodash._createpadding@3.6.1
│ │ │ │ ├── lodash.pad@3.1.1
│ │ │ │ ├── lodash.padleft@3.1.1
│ │ │ │ ├── lodash.padright@3.1.1
│ │ │ │ ├── lodash.repeat@3.0.1
│ │ │ │ ├── mime-db@1.19.0
│ │ │ │ ├── mime-types@2.1.7
│ │ │ │ ├── minimist@0.0.8
│ │ │ │ ├── mkdirp@0.5.1
│ │ │ │ ├── nan@2.1.0
│ │ │ │ ├─┬ node-pre-gyp@0.6.17
│ │ │ │ │ └─┬ nopt@3.0.6
│ │ │ │ │   └── abbrev@1.0.7
│ │ │ │ ├── node-uuid@1.4.7
│ │ │ │ ├── npmlog@2.0.0
│ │ │ │ ├── oauth-sign@0.8.0
│ │ │ │ ├── once@1.1.1
│ │ │ │ ├── pinkie@2.0.1
│ │ │ │ ├── pinkie-promise@2.0.0
│ │ │ │ ├── qs@5.2.0
│ │ │ │ ├─┬ rc@1.1.5
│ │ │ │ │ └── minimist@1.2.0
│ │ │ │ ├── readable-stream@1.1.13
│ │ │ │ ├── request@2.67.0
│ │ │ │ ├─┬ rimraf@2.4.4
│ │ │ │ │ └─┬ glob@5.0.15
│ │ │ │ │   ├─┬ inflight@1.0.4
│ │ │ │ │   │ └── wrappy@1.0.1
│ │ │ │ │   ├── inherits@2.0.1
│ │ │ │ │   ├─┬ minimatch@3.0.0
│ │ │ │ │   │ └─┬ brace-expansion@1.1.1
│ │ │ │ │   │   ├── balanced-match@0.2.1
│ │ │ │ │   │   └── concat-map@0.0.1
│ │ │ │ │   ├─┬ once@1.3.3
│ │ │ │ │   │ └── wrappy@1.0.1
│ │ │ │ │   └── path-is-absolute@1.0.0
│ │ │ │ ├── semver@5.1.0
│ │ │ │ ├── sntp@1.0.9
│ │ │ │ ├─┬ sshpk@1.7.0
│ │ │ │ │ └── assert-plus@0.2.0
│ │ │ │ ├── string_decoder@0.10.31
│ │ │ │ ├── stringstream@0.0.5
│ │ │ │ ├── strip-ansi@3.0.0
│ │ │ │ ├── strip-json-comments@1.0.4
│ │ │ │ ├── supports-color@2.0.0
│ │ │ │ ├── tar@2.2.1
│ │ │ │ ├─┬ tar-pack@3.1.0
│ │ │ │ │ ├─┬ readable-stream@1.0.33
│ │ │ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ │ │ ├── inherits@2.0.1
│ │ │ │ │ │ ├── isarray@0.0.1
│ │ │ │ │ │ └── string_decoder@0.10.31
│ │ │ │ │ └── rimraf@2.2.8
│ │ │ │ ├── tough-cookie@2.2.1
│ │ │ │ ├── tunnel-agent@0.4.1
│ │ │ │ ├── tweetnacl@0.13.2
│ │ │ │ ├── uid-number@0.0.3
│ │ │ │ ├── verror@1.3.6
│ │ │ │ └── xtend@4.0.1
│ │ │ ├── glob-parent@2.0.0
│ │ │ ├── inherits@2.0.1
│ │ │ ├─┬ is-binary-path@1.0.1
│ │ │ │ └── binary-extensions@1.4.0
│ │ │ ├─┬ is-glob@2.0.1
│ │ │ │ └── is-extglob@1.0.0
│ │ │ ├── path-is-absolute@1.0.0
│ │ │ └─┬ readdirp@2.0.0
│ │ │   └─┬ readable-stream@2.0.5
│ │ │     ├── core-util-is@1.0.2
│ │ │     ├── isarray@0.0.1
│ │ │     ├── process-nextick-args@1.0.6
│ │ │     ├── string_decoder@0.10.31
│ │ │     └── util-deprecate@1.0.2
│ │ ├── escape-string-regexp@1.0.4
│ │ └── graceful-fs@4.1.2
│ ├─┬ hexo-i18n@0.2.1
│ │ └── sprintf-js@1.0.3
│ ├─┬ hexo-util@0.1.7
│ │ ├── ent@2.2.0
│ │ └── highlight.js@8.9.1
│ ├─┬ js-yaml@3.4.6
│ │ ├─┬ argparse@1.0.3
│ │ │ └── sprintf-js@1.0.3
│ │ ├── esprima@2.7.1
│ │ └── inherit@2.2.2
│ ├── lodash@3.10.1
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.2
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ ├── moment@2.10.6
│ ├── moment-timezone@0.3.1
│ ├─┬ nunjucks@1.3.4
│ │ ├─┬ chokidar@0.12.6
│ │ │ ├── async-each@0.1.6
│ │ │ ├─┬ fsevents@0.3.8
│ │ │ │ └── nan@2.1.0
│ │ │ └─┬ readdirp@1.3.0
│ │ │   ├── graceful-fs@2.0.3
│ │ │   ├─┬ minimatch@0.2.14
│ │ │   │ ├── lru-cache@2.7.3
│ │ │   │ └── sigmund@1.0.1
│ │ │   └─┬ readable-stream@1.0.33
│ │ │     ├── core-util-is@1.0.2
│ │ │     ├── inherits@2.0.1
│ │ │     ├── isarray@0.0.1
│ │ │     └── string_decoder@0.10.31
│ │ └─┬ optimist@0.6.1
│ │   ├── minimist@0.0.10
│ │   └── wordwrap@0.0.3
│ ├── pretty-hrtime@1.0.1
│ ├─┬ strip-indent@1.0.1
│ │ └── get-stdin@4.0.1
│ ├─┬ swig@1.4.2
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ uglify-js@2.4.24
│ │   ├── async@0.2.10
│ │   ├─┬ source-map@0.1.34
│ │   │ └── amdefine@1.0.0
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.5.4
│ │     ├── camelcase@1.2.1
│ │     ├─┬ decamelize@1.1.2
│ │     │ └── escape-string-regexp@1.0.4
│ │     ├── window-size@0.1.0
│ │     └── wordwrap@0.0.2
│ ├─┬ swig-extras@0.0.1
│ │ └─┬ markdown@0.5.0
│ │   └── nopt@2.1.2
│ ├── text-table@0.2.0
│ ├─┬ through2@1.1.1
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── xtend@4.0.1
│ ├─┬ tildify@1.1.2
│ │ └── os-homedir@1.0.1
│ ├── titlecase@1.0.2
│ └─┬ warehouse@1.0.3
│   ├── cuid@1.2.5
│   ├── graceful-fs@4.1.2
│   └─┬ JSONStream@1.0.7
│     ├── jsonparse@1.2.0
│     └── through@2.3.8
├─┬ hexo-generator-archive@0.1.4
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.1.1
├─┬ hexo-generator-category@0.1.3
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.1.1
├─┬ hexo-generator-index@0.2.0
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@4.0.1
├─┬ hexo-generator-tag@0.1.2
│ ├─┬ hexo-pagination@0.0.2
│ │ └── utils-merge@1.0.0
│ └── object-assign@2.1.1
├─┬ hexo-renderer-asciidoc@1.1.5
│ ├─┬ asciidoctor.js@1.5.3
│ │ ├── opal-npm-wrapper@0.9.0-beta2
│ │ └── xmlhttprequest@1.7.0
│ ├─┬ cheerio@0.19.0
│ │ ├─┬ css-select@1.0.0
│ │ │ ├── boolbase@1.0.0
│ │ │ ├── css-what@1.0.0
│ │ │ ├─┬ domutils@1.4.3
│ │ │ │ └── domelementtype@1.3.0
│ │ │ └── nth-check@1.0.1
│ │ ├─┬ dom-serializer@0.1.0
│ │ │ └── domelementtype@1.1.3
│ │ ├─┬ htmlparser2@3.8.3
│ │ │ ├── domelementtype@1.3.0
│ │ │ ├── domhandler@2.3.0
│ │ │ ├── domutils@1.5.1
│ │ │ ├── entities@1.0.0
│ │ │ └─┬ readable-stream@1.1.13
│ │ │   ├── core-util-is@1.0.2
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ └── lodash@3.10.1
│ ├── entities@1.1.1
│ └─┬ hexo-util@0.1.7
│   ├── bluebird@2.10.2
│   ├── ent@2.2.0
│   └── highlight.js@8.9.1
├─┬ hexo-renderer-ejs@0.1.1
│ ├── ejs@1.0.0
│ └── object-assign@4.0.1
├─┬ hexo-renderer-marked@0.2.8
│ ├─┬ hexo-util@0.5.1
│ │ ├── bluebird@3.1.1
│ │ ├─┬ camel-case@1.2.2
│ │ │ ├─┬ sentence-case@1.1.3
│ │ │ │ └── lower-case@1.1.3
│ │ │ └── upper-case@1.1.3
│ │ ├── highlight.js@9.1.0
│ │ └── html-entities@1.2.0
│ ├── marked@0.3.5
│ ├── object-assign@4.0.1
│ └─┬ strip-indent@1.0.1
│   └── get-stdin@4.0.1
├─┬ hexo-renderer-stylus@0.3.0
│ ├─┬ nib@1.1.0
│ │ └─┬ stylus@0.49.3
│ │   ├── css-parse@1.7.0
│ │   ├─┬ debug@2.2.0
│ │   │ └── ms@0.7.1
│ │   ├─┬ glob@3.2.11
│ │   │ ├── inherits@2.0.1
│ │   │ └─┬ minimatch@0.3.0
│ │   │   ├── lru-cache@2.7.3
│ │   │   └── sigmund@1.0.1
│ │   ├── mkdirp@0.3.5
│ │   ├── sax@0.5.8
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@1.0.0
│ └─┬ stylus@0.52.4
│   ├── css-parse@1.7.0
│   ├─┬ debug@2.2.0
│   │ └── ms@0.7.1
│   ├─┬ glob@3.2.11
│   │ ├── inherits@2.0.1
│   │ └─┬ minimatch@0.3.0
│   │   ├── lru-cache@2.7.3
│   │   └── sigmund@1.0.1
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├── sax@0.5.8
│   └─┬ source-map@0.1.43
│     └── amdefine@1.0.0
└─┬ hexo-server@0.1.3
  ├── bluebird@3.1.1
  ├─┬ chalk@1.1.1
  │ ├── ansi-styles@2.1.0
  │ ├── escape-string-regexp@1.0.4
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├─┬ strip-ansi@3.0.0
  │ │ └── ansi-regex@2.0.0
  │ └── supports-color@2.0.0
  ├─┬ compression@1.6.0
  │ ├─┬ accepts@1.3.0
  │ │ ├─┬ mime-types@2.1.9
  │ │ │ └── mime-db@1.21.0
  │ │ └── negotiator@0.6.0
  │ ├── bytes@2.1.0
  │ ├─┬ compressible@2.0.6
  │ │ └── mime-db@1.21.0
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── on-headers@1.0.1
  │ └── vary@1.1.0
  ├─┬ connect@3.4.0
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├─┬ finalhandler@0.4.0
  │ │ ├── escape-html@1.0.2
  │ │ ├─┬ on-finished@2.3.0
  │ │ │ └── ee-first@1.1.1
  │ │ └── unpipe@1.0.0
  │ ├── parseurl@1.3.0
  │ └── utils-merge@1.0.0
  ├── mime@1.3.4
  ├─┬ morgan@1.6.1
  │ ├── basic-auth@1.0.3
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── depd@1.0.1
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ └── on-headers@1.0.1
  ├── object-assign@4.0.1
  ├── opn@3.0.3
  └─┬ serve-static@1.10.0
    ├── escape-html@1.0.2
    ├── parseurl@1.3.0
    └─┬ send@0.13.0
      ├── debug@2.2.0
      ├── depd@1.0.1
      ├── destroy@1.0.3
      ├── etag@1.7.0
      ├── fresh@0.3.0
      ├─┬ http-errors@1.3.1
      │ └── inherits@2.0.1
      ├── ms@0.7.1
      ├─┬ on-finished@2.3.0
      │ └── ee-first@1.1.1
      ├── range-parser@1.0.3
      └── statuses@1.2.1
```

**Comment by hcoona** [comment]
Thank you for your kind report! And sorry for the late response. I'm quite busy in recent days because it is soon coming the Chinese new year.

Seems that there is no direct reason to cause such a problem. I would try to reproduce it, but may be somehow late. Sorry for that.

**Comment by tilmans** [comment]
gong xi fa cai - i'll give it another look later, maybe one of the dependencies has issues which are resolved now.

**Comment by agibalov** [comment]
Just faced the same issue with Node v5.0.0 and npm 3.3.6. It looks like the problem is somewhere outside hexo-renderer-plugin, because the failure happens during `asciidoctor.js` initialization. I've put this `1.js` into `scripts` directory ("a light-weight plugin"):

```
require('asciidoctor.js')();
```

and it happened. Perhaps a monkey patch somewhere?

**Comment by hcoona** [comment]
According to http://asciidoctor.org/docs/install-and-use-asciidoctorjs/

> The asciidoctor.js project is a direct port of Asciidoctor from Ruby to JavaScript using the Opal Ruby-to-JavaScript cross compiler.

There may be conflicts between asciidoctor.js and other dependencies in hexo. We need to locate the root cause and report it to upstream.

Thank you @loki2302 , you made a good minimal steps to reproduce it.

**Comment by fusion809** [comment]
I have experienced the same error with Node.js 5.10.1 and NPM 3.8.6. I also noticed this odd behaviour when installing this plugin:

``` bash
$ npm install hexo-renderer-asciidoc --save
hexo-site@0.0.0 /home/fusion809/GitHub/hexo-site
├── asciidoctor.js@1.5.5-1  extraneous
└── JSONStream@1.0.6  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
```

If relevant I am operating on Arch Linux.

**Comment by fusion809** [comment]
Oh and I found out why I am getting this error. Hexo 3.2.0 requires Warehouse 2.2.0, which in turn requires JSONStream&geq;1.0.7. So it installs JSONStream 1.1.1 which conflicts with JSONStream 1.0.6

**Comment by bwklein** [comment]
I have the same issue.  Is there a good solution for this?

**Comment by hcoona** [comment]
Sorry for late response. It currently works with Hexo 3.2.2 with Node 6.10.0.
